name: transactional-outbox-cdc-thesis

services:

  subscription-db:
    image: postgres:18.6
    container_name: subscription-db
    environment:
      POSTGRES_DB: ${SUBSCRIPTION_DB_NAME}
      POSTGRES_USER: ${SUBSCRIPTION_DB_USER}
      POSTGRES_PASSWORD: ${SUBSCRIPTION_DB_PASSWORD}
    command:
      - postgres
      - -c
      - wal_level=logical
    ports:
      - "${SUBSCRIPTION_DB_PORT}:5432"
    volumes:
      - subscription-db-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SUBSCRIPTION_DB_USER} -d ${SUBSCRIPTION_DB_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  subscription-db-data:
