springdotenv:
  directory: ../../

spring:
  application:
    name: subscription-service

  datasource:
    url: jdbc:postgresql://${SUBSCRIPTION_DB_HOST}:${SUBSCRIPTION_DB_PORT}/${SUBSCRIPTION_DB_NAME}
    username: ${SUBSCRIPTION_DB_USER}
    password: ${SUBSCRIPTION_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level [traceId:%X{traceId} spanId:%X{spanId}] %logger{36} - %msg%n"
